### ISSUE TITLE
No python3 provider found

### ISSUE THREAD

**Issue by Pritep** [martineausimon/nvim-bard#2]
![20230717_162150](https://github.com/martineausimon/nvim-bard/assets/63929457/d86a0f2c-8f94-46e2-a8a6-0f17da85ba50)

I followed the instructions in lazy.nvim, and in  nvim exist global variable python3

**Comment by martineausimon** [comment]
Please can you test `:checkhealth provider` to see if a python provider is available for neovim?

If not you can install [pynvim](https://github.com/neovim/pynvim) with the following command :

```bash
pip install pynvim
```

Keep me informed!

**Comment by Pritep** [comment]
Thanks for change the title.

I'd exec :checkhealth provider, and it return this:
![20230719_125545](https://github.com/martineausimon/nvim-bard/assets/63929457/c41ec057-8349-480f-8426-a14735350d4e)
And then I'd install pynvim

**Comment by martineausimon** [comment]
Looks like you don't have a python provider. Can you try again after installing pynvim?
```bash
pip install pynvim
```

**Comment by Pritep** [comment]
Yeah, still the same

**Comment by martineausimon** [comment]
Have you thought about removing the global variable `loaded_python3_provider=0`?

**Comment by Pritep** [comment]
I have been put this code in my init.lua
![20230719_132740](https://github.com/martineausimon/nvim-bard/assets/63929457/6721ad6c-7159-44d8-8a61-670c7307b8b6)
Then :checkhealth provider return:
![20230719_133305](https://github.com/martineausimon/nvim-bard/assets/63929457/24120841-f7e2-4a41-b3a2-409479921d40)

**Comment by martineausimon** [comment]
You should delete this variable :

In your config :

```lua
vim.api.nvim_del_var('loaded_python3_provider')
```

Or in neovim :

```vim
:unlet g:loaded_python3_provider
```

**Comment by Pritep** [comment]
Thank you so much. It works
I'd exec in cmd :unlet...
