### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by kobzar** [martineausimon/nvim-bard#5]
The plugin don work more

Error executing vim.schedule lua callback: function provider#python3#Call, line 18: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/bardapi/core.py", line 78, in __init__
    self.SNlM0e = self._get_snim0e()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bardapi/core.py", line 154, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.
stack traceback:
	[C]: in function 'execute'
	.../.local/share/nvim/lazy/nvim-bard/lua/nvim-bard/bard.lua:34: in function 'load'
	...share/nvim/lazy/nvim-bard/lua/nvim-bard/layout/popup.lua:114: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: function provider#python3#Call, line 18: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'bard' is not defined
stack traceback:
	[C]: in function 'execute'
	.../.local/share/nvim/lazy/nvim-bard/lua/nvim-bard/bard.lua:41: in function 'ask'
	...share/nvim/lazy/nvim-bard/lua/nvim-bard/layout/popup.lua:123: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by martineausimon** [comment]
Please check https://github.com/martineausimon/nvim-bard/issues/3

**Comment by kobzar** [comment]
I do this before create the issue.
It was worked some time ago before i make last commit for this plugins and now i have a error

But i found some strange moment
In my browser all working fine, but after full refresh the page my cookies was changed. 
So, i update it in my config and now all working fine. 

It will every time when i refresh the bard tab in browser?

**Comment by martineausimon** [comment]
Yes, this is what is specified in issue #3 (and on the bardapi page). The last commit was several months ago, I don't think that's where the error comes from.
Unfortunately this makes this plugin almost unusable, as specified in README.md :

>Writing this plugin was a lot of fun, but I don't recommend using it for anything other than experimentation.
>It works with bardapi which is not an official API and which can stop working at the slightest change in Bard's policy. Since August, it seems that it is necessary to update the cookie values regularly.
>Also, this AI is quite slow and seems to me less efficient than ChatGPT for coding.
